### ISSUE TITLE
Verify configuration doesn't seem to work

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/manage-github-apps#51]
With a configuration of...

```json
{
  "owner": "Financial-Times",
  "installations": [
    {
      "test": 442071,
      "comment": "Customer Products Tako"
    }
  ]
}
```

Running `npx github:financial-times/manage-github-apps verify-config manage-github-apps/only-tako.json` does not result in any errors or a non-zero status code.

**Comment by simonplend** [comment]
Here's the output I get when I recreate that scenario on my machine:

```
$ npx github:financial-times/manage-github-apps validate-config only-tako.json 
npx: installed 84 in 4.317s
manage-github-apps validate-config

Validate a JSON configuration against the manage-github-apps JSON schema

Options:
  --version     Show version number                                    [boolean]
  --help        Show help                                              [boolean]
  --config, -c  Path to JSON configuration (URL or local filepath)
                                                             [string] [required]

Missing required argument: config
```

As the last line of that output indicates, the path to the config (URL or local filepath) needs to be specified as a named option: `--config manage-github-apps/only-tako.json`

When I correct the command to pass the config path as a named option the `validate-config` command works as expected:

```
$ npx github:financial-times/manage-github-apps validate-config --config only-tako.json 
npx: installed 84 in 6.894s
✖ ERROR: Config#load: The config is invalid:

- 'installations.0.id' is required (value: {"test":442071,"comment":"Customer Products Tako"})
```

**Comment by sjparkinson** [comment]
Ah, not sure I'm a fan of a named option here. Wasn't intuitive.

Will update the tests so it is getting checked at least, though I'm not getting the same output as you. The build in CircleCI shows the command returning no output.

**Comment by simonplend** [comment]
Discussed in person: the wrong command (`verify-config`) was being used, and yargs wasn't throwing an error. Raising an issue to fix.

**Comment by simonplend** [comment]
Related issues:

- https://github.com/Financial-Times/manage-github-apps/issues/54
- https://github.com/Financial-Times/tooling-helpers/issues/37
